### ISSUE TITLE
Occasional, inconsistent "Converting circular structure to JSON" error

### ISSUE THREAD

**Issue by querkmachine** [frctl/nunjucks-engine#5] opened 2018-08-20 17:02 UTC
I will occasionally encounter an error very much like the one below when editing a component's HTML or context data. Upon encountering it—through the page auto-refreshing or through refreshing the Fractal page manually—Fractal's auto-compilation will cease working and the local server will stop. 

```
Unhandled rejection TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at source.resolve.then.context (/Users/kim/Sites/ClientName/node_modules/@frctl/nunjucks/src/extensions/render.js:41:43)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at tryCatcher (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/kim/Sites/ClientName/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

(Actual client's name replaced with `ClientName` to protect the innocent.) 

I cannot offer an explanation or reproduction case for why this happens. Sometimes adding a new line of context data will trigger it—sometimes removing that line will resolve it, sometimes it won't; sometimes editing the key/value of the line in YAML will resolve it, sometimes it won't.) 

Likewise when editing HTML. Sometimes a component will be fine, but trying to render it from another component (via `{% render '@component' %}`) will cause the error. There seems to be little consistency to it occurring, other than it occurs.

Sorry for the vague issue report, but I can't find any mention or fix for this this elsewhere, and figured this would be the best place for it. 

Node version: 10.4.0
Fractal version: 1.1.7
Fractal Nunjucks version: 1.0.3
Nunjucks version: 2.5.2

**Comment by querkmachine** [comment] 2018-08-20 17:33
Update: After a bunch of commenting things out and running Fractal I've seemingly isolated this to the `panels` option in my Mandelbrot configuration. Commenting it out has gotten rid of the above error in at least two instances where it was occurring. 

I still can't explain why it was only happening in certain components with certain code/context data. It's a mystery.

**Comment by LeBenLeBen** [comment] 2018-09-07 10:20
I can reproduce your issue with the same error in `@frctl/nunjucks/src/extensions/render.js:41:43` even if my call stack is a bit different. The problem occurs systematically when I run `fractal build`.

Removing the `panels` entry from the Mandelbrot config object does indeed prevent the errors for me as well. I've spent some time trying to debug it but could not figure out how this theme option can have such impact on some components rendering.

**Comment by LeBenLeBen** [comment] 2018-09-30 15:57
The circular reference seems to happen at `rootContext._env._config.docs.markdown.renderer.options.renderer` which is a reference to the renderer itself two levels up, at `rootContext._env._config.docs.markdown.renderer`.

One part of the issue seems to be [this line](https://github.com/frctl/fractal/blob/1aed327df0f8e20936f70fb9c281f240590db6df/src/core/markdown.js#L25), since commenting it allows the build to complete. However it doesn't really explain the circular reference…

**Comment by LeBenLeBen** [comment] 2020-02-12 09:06
This has been fixed in https://github.com/frctl/fractal/pull/473

**Closed as completed by LeBenLeBen** 2020-02-12 09:06 UTC
